# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/sharks', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Shark. As you add validations to Shark, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Shark.create! valid_attributes
      get sharks_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      shark = Shark.create! valid_attributes
      get shark_url(shark)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_shark_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      shark = Shark.create! valid_attributes
      get edit_shark_url(shark)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Shark' do
        expect do
          post sharks_url, params: { shark: valid_attributes }
        end.to change(Shark, :count).by(1)
      end

      it 'redirects to the created shark' do
        post sharks_url, params: { shark: valid_attributes }
        expect(response).to redirect_to(shark_url(Shark.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Shark' do
        expect do
          post sharks_url, params: { shark: invalid_attributes }
        end.to change(Shark, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post sharks_url, params: { shark: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested shark' do
        shark = Shark.create! valid_attributes
        patch shark_url(shark), params: { shark: new_attributes }
        shark.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the shark' do
        shark = Shark.create! valid_attributes
        patch shark_url(shark), params: { shark: new_attributes }
        shark.reload
        expect(response).to redirect_to(shark_url(shark))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        shark = Shark.create! valid_attributes
        patch shark_url(shark), params: { shark: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested shark' do
      shark = Shark.create! valid_attributes
      expect do
        delete shark_url(shark)
      end.to change(Shark, :count).by(-1)
    end

    it 'redirects to the sharks list' do
      shark = Shark.create! valid_attributes
      delete shark_url(shark)
      expect(response).to redirect_to(sharks_url)
    end
  end
end
